version: "3.9"

services:
  staging-backend:
    container_name: better-edibles-staging-backend
    build:
      context: ./staging/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5100:5100"
    env_file:
      - ./env/common.env
      - ./env/staging.env

  staging-frontend:
    container_name: better-edibles-staging-frontend
    build:
      context: ./staging/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV: staging
    restart: always
    ports:
      - "127.0.0.1:3100:3000"
    env_file:
      - ./env/common.env
      - ./env/staging.env
