name: Deploy Frontend (Staging)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to staging server
        uses: appleboy/ssh-action@v1.0.0
        env: # ðŸ‘ˆ ADD THIS
          NEXT_PUBLIC_ENV: staging # ðŸ‘ˆ ADD THIS
        with:
          host: 143.244.182.86
          username: deploy
          key: ${{ secrets.PROD_SSH_KEY }}
          command_timeout: 25m
          script: |
            cd /opt/apps/better-edibles/staging/frontend
            git pull origin staging

            cd /opt/apps/better-edibles
            docker compose -f docker-compose.staging.yml up -d --build staging-frontend
